version: '3'

services:
  backend:
    ports:
     - 3030:80
     - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:debug
    volumes:
      - ./src:/srv/www/site/src
      - ./config:/srv/www/site/config

  database:
    ports:
    - "3306:3306"