version: '3'

services:
  backend:
    ports:
      - 80
      - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - database
    volumes:
      - ./volumes/backend:/data/ia_trading/uploads
      - ./logs:/srv/www/ia_trading/logs

  database:
    container_name: ia_trading.vm-database
    build:
      context: database
      dockerfile: Dockerfile
    logging:
      driver: none
    environment:
    - MYSQL_USER=user
    - MYSQL_DATABASE=ia_trading_db
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake"
    restart: always
    ports:
      - 3306
